# Generated by Django 4.1.2 on 2022-10-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1997-06-12"),
            preserve_default=False,
        ),
    ]
